apiVersion: v1
kind: Service
metadata:
  annotations: 
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.dnsname.name }}
  name: {{ include "poke-helm-azure.fullname" . }}
  labels:
    {{- include "poke-helm-azure.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "poke-helm-azure.selectorLabels" . | nindent 4 }}
